name: My Application
base-url: default.com
default-contact-email: dev@message.co.uk
default-email-from:
  email: noreply@default.com
  name: My Application
csrf-secret: CHANGE THIS FOR EACH INSTALLATION
session-namespace: cog