twitter:
  name: Mothership_Ecom
  slug: # slug to link to
facebook:
  name: mothership.ecommerce
  slug: # slug to link to
instagram:
  name: # instagram
  slug: # slug to link to
pintrest:
  name: # pinterest
  slug: # slug to link to